# Generated by Django 4.0.4 on 2022-05-11 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_filesdoc_fileszip_alter_filesserv_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilesDoc',
        ),
        migrations.DeleteModel(
            name='FilesZip',
        ),
        migrations.AlterModelOptions(
            name='filesserv',
            options={'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
    ]
