# Generated by Django 4.0.4 on 2022-05-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_filesdoc_delete_fileszip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocServ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(max_length=255, upload_to='')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документ',
            },
        ),
    ]
