# Generated by Django 4.0.4 on 2022-05-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_docserv'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilesDecrypt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(max_length=255, upload_to='')),
                ('file_serv', models.FileField(max_length=255, upload_to='decrypt/')),
            ],
            options={
                'verbose_name': 'Decrypt',
                'verbose_name_plural': 'Decrypt',
            },
        ),
    ]
