# Generated by Django 4.0.4 on 2022-05-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_filesdecrypt_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesdecrypt',
            name='doc',
            field=models.FileField(max_length=255, upload_to='decrypto/'),
        ),
        migrations.AlterField(
            model_name='filesdecrypt',
            name='file_serv',
            field=models.FileField(max_length=255, upload_to='decrypto/'),
        ),
    ]
