# Generated by Django 4.0.4 on 2022-05-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_filesdecrypt_doc_alter_filesdecrypt_file_serv'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilesCert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(max_length=255, upload_to='')),
                ('file_serv', models.FileField(max_length=255, upload_to='')),
            ],
            options={
                'verbose_name': 'Файл сертификата',
                'verbose_name_plural': 'Файлы сертификата',
            },
        ),
    ]
