# Generated by Django 4.0.4 on 2022-05-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_filescert'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertGost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='filescert',
            name='file_serv',
        ),
        migrations.AlterField(
            model_name='filescert',
            name='doc',
            field=models.FileField(max_length=255, upload_to='decrypto/'),
        ),
    ]
